export const initialProducts = [
    {
      name: "Banana",
      price: "30.00",
      id: 1,
      count: 0,
      availableProduct: 0,
      imageId: "GaO3Dq0b",
      category: "fruits",
    },
    {
      name: "Cabbage",
      price: "15.00",
      previousPrice: "5.00gh",
      id: 2,
      count: 0,
      availableProduct: 5,
      imageId: "pOI2ysTb",
      category: "vegetables",
    },
    {
      name: "Pineapple",
      price: "50.50",
      id: 3,
      count: 0,
      availableProduct: 80,
      imageId: "3XdqWjIb",
      category: "fruits",
    },
    {
      name: "Pepper",
      price: "5.00",
      id: 4,
      count: 0,
      availableProduct: 20,
      imageId: "hSzg2NRb",
      category: "vegetables",
    },
    {
      name: "Tomatoes",
      price: "10.50",
      id: 5,
      count: 0,
      availableProduct: 25,
      imageId: "fiDTCPFb",
      category: "vegetables",
    },
    {
      name: "Orange(color)",
      price: "4.22",
      id: 6,
      count: 0,
      availableProduct: 35,
      imageId: "FoZWruFb",
      category: "fruits",
    },
    {
      name: "Orange",
      price: "2.50",
      id: 7,
      count: 0,
      availableProduct: 35,
      imageId: "LuIDHn1b",
    },
   
    {
      name: "Apple",
      price: "2.00",
      id: 8,
      count: 0,
      availableProduct: 10,
      imageId: "0I998ijb",
      category: "fruits",
    },
    {
      name: "Cherries",
      price: "15.23",
      id: 9,
      count: 0,
      availableProduct: 10,
      imageId: "is4P1Tab",
      category: "fruits",
    },
    {
      name: "Grapes",
      price: "2.00",
      id: 10,
      count: 0,
      availableProduct: 10,
      imageId: "rfak9fPb",
      category: "fruits",
    },
    {
      name: "Onion",
      price: "10.50",
      id: 11,
      count: 0,
      availableProduct: 25,
      imageId: "xlJGTUTb",
      category: "vegetables",
    },
    {
      name: "Garlic",
      price: "10.50",
      id: 12,
      count: 0,
      availableProduct: 25,
      imageId: "YLw1ZdJb",
      category: "vegetables",
    },
    {
      name: "Ginga",
      price: "10.50",
      id: 13,
      count: 0,
      availableProduct: 25,
      imageId: "CibJ9Fnb",
      category: "vegetables",
    },
    {
      name: "Spring onion",
      price: "10.50",
      id: 14,
      count: 0,
      availableProduct: 25,
      imageId: "smM1BENb",
      category: "vegetables",
    },
    {
      name: "Mushroom",
      price: "10.50",
      id: 15,
      count: 0,
      availableProduct: 25,
      imageId: "Gk5l7VLb",
      category: "vegetables",
    },
    {
      name: "Corn",
      price: "10.50",
      id: 16,
      count: 0,
      availableProduct: 25,
      imageId: "5qJu1NYb",
      category: "vegetables",
    },
    ,
    {
      name: "Orange(color)",
      price: "4.22",
      id: 17,
      count: 0,
      availableProduct: 35,
      imageId: "FoZWruFb",
      category: "fruits",
    },
    {
      name: "Orange",
      price: "2.50",
      id: 18,
      count: 0,
      availableProduct: 35,
      imageId: "LuIDHn1b",
    },
    ,
    {
      name: "Orange(color)",
      price: "4.22",
      id: 19,
      count: 0,
      availableProduct: 35,
      imageId: "FoZWruFb",
      category: "fruits",
    },
    {
      name: "Orange",
      price: "2.50",
      id: 20,
      count: 0,
      availableProduct: 35,
      imageId: "LuIDHn1b",
    },
    ,
    {
      name: "Orange(color)",
      price: "4.22",
      id: 21,
      count: 0,
      availableProduct: 35,
      imageId: "FoZWruFb",
      category: "fruits",
    },
    {
      name: "Orange",
      price: "2.50",
      id: 22,
      count: 0,
      availableProduct: 35,
      imageId: "LuIDHn1b",
    },
  ];
  